spring.application.name=LibraryCRM

# SERVER PORT
server.port=8080


# DATABASE CONNECTION (MySQL)
spring.datasource.url=jdbc:mysql://avnadmin:AVNS_OSWcDAcGEIL9811UNyC@librarycrm-30032026-nhatledev2003-ecommerce-be.g.aivencloud.com:17912/library_crm_db?ssl-mode=REQUIRED&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_OSWcDAcGEIL9811UNyC
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# JPA / HIBERNATE SETTINGS
spring.jpa.hibernate.ddl-auto=update
# In câu l?nh SQL ra console ?? d? debug
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


# CUSTOM SECURITY & JWT PROPERTIES
application.security.jwt.secret-key=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
# Th?i gian s?ng c?a token: 86400000 ms = 1 ngày
application.security.jwt.expiration=86400000